-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["1x1_bomb"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16.5, -15.5  ,  16.5, 15.5  ,  -16.5, 15.5  ,  -16.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x1_combo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14.5, -14.5  ,  14.5, 15.5  ,  -15.5, 15.5  ,  -15.5, -14.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x1_draggable"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14.5, -15.5  ,  14.5, 15.5  ,  -15.5, 15.5  ,  -15.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x1_magnet"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35,  
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   15.5, -14.5  ,  15.5, 15.5  ,  -15.5, 15.5  ,  -15.5, -14.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x1_standard"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   15.5, -14.5  ,  15.5, 15.5  ,  -15.5, 15.5  ,  -15.5, -14.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x4_bomb"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, -14.5  ,  57.5, 15.5  ,  -57.5, 15.5  ,  -57.5, -14.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x4_combo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, -15.5  ,  57.5, 15.5  ,  -58.5, 15.5  ,  -58.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x4_draggable"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56.5, -15.5  ,  56.5, 15.5  ,  -57.5, 15.5  ,  -57.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["1x4_standard"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, -15.5  ,  57.5, 15.5  ,  -57.5, 15.5  ,  -57.5, -15.5  }
                    }
                    
                    
                    
		}
		
		,
		["2x2_bomb"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   29, -27  ,  29, 28  ,  -28, 28  ,  -28, -27  }
                    }
                    
                    
                    
		}
		
		, 
		["2x2_combo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -27  ,  28, 30  ,  -28, 30  ,  -28, -27  }
                    }
                    
                    
                    
		}
		
		, 
		["2x2_draggable"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   29, -28  ,  29, 30  ,  -29, 30  ,  -29, -28  }
                    }
                    
                    
                    
		}
		
		, 
		["2x2_magnet"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   29, -28  ,  29, 30  ,  -28, 30  ,  -28, -28  }
                    }
                    
                    
                    
		}
		
		, 
		["2x2_standard"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1.2, friction = 0.4, bounce = 0.35, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -28  ,  28, 30  ,  -29, 30  ,  -29, -28  }
                    }
                    
                    
                    
		}
		,
		["levelground_01"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -235, 115  ,  -240, 160  ,  -320, -126  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, 115  ,  240, 160  ,  -240, 160  ,  -235, 115  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  235, 114  ,  291, -133  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  131, 115  ,  165, 111  ,  211, 111  ,  235, 114  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  107, 117  ,  131, 115  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 108  ,  29, 109  ,  78, 113  ,  107, 117  ,  240, 160  ,  -124, 117  ,  -91, 111  }
                    }
                    
                    
                    
		}
		
		, 
		["levelground_02"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   211, 111  ,  235, 114  ,  240, 160  ,  116, 118  ,  165, 111  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -235, 115  ,  -240, 160  ,  -304, -115  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, 115  ,  240, 160  ,  -240, 160  ,  -235, 115  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  235, 114  ,  303, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 108  ,  29, 109  ,  78, 113  ,  240, 160  ,  -124, 117  ,  -91, 111  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  78, 113  ,  116, 118  }
                    }
                    
                    
                    
		}
		
		, 
		["levelground_00"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -235, 115  ,  -240, 160  ,  -312, -101  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, 115  ,  240, 160  ,  -240, 160  ,  -235, 115  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  235, 114  ,  309, -110  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  113, 118  ,  131, 115  ,  165, 111  ,  211, 111  ,  235, 114  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 108  ,  29, 109  ,  78, 113  ,  101, 117  ,  240, 160  ,  -124, 117  ,  -91, 111  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   240, 160  ,  101, 117  ,  113, 118  }
                    }
                    
                    
                    
		}
		,
		["statue_b_1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 24.5  ,  25, 30.5  ,  21, 34.5  ,  18, 15.5  ,  24, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -18, 15.5  ,  -22, 32.5  ,  -25, 30.5  ,  -25, 25.5  ,  -24, 16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18, 15.5  ,  22, -5.5  ,  26, -2.5  ,  30, 7.5  ,  27, 13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, 4.5  ,  -26, -2.5  ,  -22, -5.5  ,  -18, 15.5  ,  -27, 13.5  ,  -29, 11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18, 15.5  ,  -16, -17.5  ,  11, -25.5  ,  17, -18.5  ,  22, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16, -17.5  ,  18, 15.5  ,  21, 34.5  ,  20, 38.5  ,  -18, 15.5  ,  -22, -5.5  ,  -21, -10.5  ,  -18, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -18, 15.5  ,  20, 38.5  ,  -20, 38.5  ,  -22, 32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, -27.5  ,  11, -25.5  ,  -16, -17.5  ,  -15, -21.5  ,  -1, -38.5  ,  1, -38.5  }
                    }
                    
                    
                    
		}
		
		, 
		["statue_s_1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12.5, 6.5  ,  11.5, -3.5  ,  15.5, 1.5  ,  15.5, 5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16.5, 1.5  ,  -15.5, -1.5  ,  -12.5, -3.5  ,  -13.5, 7.5  ,  -16.5, 5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13.5, 7.5  ,  -1.5, -21.5  ,  0.5, -21.5  ,  -11.5, 18.5  ,  -14.5, 16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11.5, 16.5  ,  -11.5, 20.5  ,  12.5, 6.5  ,  13.5, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11.5, 20.5  ,  11.5, 16.5  ,  10.5, 20.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11.5, 20.5  ,  -11.5, 18.5  ,  0.5, -21.5  ,  7.5, -13.5  ,  11.5, -3.5  ,  12.5, 6.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 9999, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1.5, -21.5  ,  -13.5, 7.5  ,  -12.5, -3.5  ,  -8.5, -13.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

